### ISSUE TITLE
Freelancers

### ISSUE THREAD

**Issue by tiborsaas** [Wiredcraft/test-frontend#1]
Hello guys, are you open to work with freelancers?

**Comment by xeodou** [comment]
@kowdermeister  
Sorry, I don't think we have any decison on hire a freelancer. The repo is a task for our condidate that who wanna join us as a full time employee. 
@hunvreus

**Comment by makara** [comment]
It depends; please submit here: https://wiredcraft.com/about/#jobs (if you are still interested). Closing.
