### ISSUE TITLE
Should totally follow mockup?

### ISSUE THREAD

**Issue by EcutDavid** [Wiredcraft/test-frontend#2]
Hi  
Recently I'm building this project in [this repo](https://github.com/EcutDavid/frontend-test/tree/David).  
The style I implemented look like this, does it permitted?  
![image](https://cloud.githubusercontent.com/assets/10692276/10049828/e8183ef4-624b-11e5-93df-3fe6414add24.png)  
[github page](http://ecutdavid.github.io/frontend-test/)

**Comment by fraserxu** [comment]
Hi @EcutDavid please follow the mockup.
- We'd like to check your JavaScript skills but also CSS, so please **do not use** "material-ui" or similar framework for the test
- Follow the mockup from designer is our daily workflow(we allow changes for real world project but for the test here no)

**Comment by EcutDavid** [comment]
@fraserxu  Thank you!

**Comment by EcutDavid** [comment]
Hi~ I remove the dependency of material-ui in [project](https://github.com/EcutDavid/frontend-test/tree/David)  
:)
[github page](http://ecutdavid.github.io/frontend-test/)
