### ISSUE TITLE
Question on test completion

### ISSUE THREAD

**Issue by peyssoa** [Wiredcraft/test-frontend#24]
Hello, I was just wondering about whether or not I should submit a PR once I have finished with the core requirements, while I continue to work on the bonus/advanced requirements, or if I should just do it once I have completed all things planned?

**Comment by flyingant** [comment]
@peyssoa Feel free to submit the PR and continue working on it. It would be great if you could show some progress during the test. Just notify us when you finish it. : )

**Comment by peyssoa** [comment]
@flyingant Alright, thank you. Will do.

**Comment by peyssoa** [comment]
Hello, just one more thing. I was wondering about the unit testing. Since this was a css oriented test, should I still go ahead and add this? Otherwise, I've completed the core functionality

**Comment by flyingant** [comment]
@peyssoa Feel free to try anything you like or you think useful.

**Comment by peyssoa** [comment]
@flyingant ok. thanks
