### ISSUE TITLE
Initial Questions 

### ISSUE THREAD

**Issue by yizucodes** [Wiredcraft/test-frontend#31]
1. Can I use vanilla CSS instead of SASS?

2. I wanted to ask you your advice in best practices when creating the collapsible row component. What are aspects of this component that I need to be careful with?

3. When collapsing back to the state level row, does the row go back to its default state? 
See image below for full explanation of edge case scenario.

![EdgeCase_RowCollapses](https://user-images.githubusercontent.com/39059002/74599476-69a9d400-50bd-11ea-8a25-38024c95bb09.jpg)

4. What kind of testing framework would you prefer? This is the first time I have been asked for unit testing on React. I have read Jest is a common framework for unit testing on React.

**Comment by flyingant** [comment]
Hi @yizu100,

This is MaYi from Wiredcraft.

>Can I use vanilla CSS instead of SASS?

Yes, of course. But I would strongly recommend using SASS instead of pure CSS. Feel free to try it and ask any question about it during the test.

>I wanted to ask you your advice in best practices when creating the collapsible row component. What are aspects of this component that I need to be careful with?

Actually, we don't have any coding restrictions or Best practices. You can try to build it along with your fancy idea. Try to show off. lol

>When collapsing back to the state level row, does the row go back to its default state?
See image below for full explanation of edge case scenario.

No necessary to care about that. You could improve it by yourself if you feel the UI/UX is not good enough. Look forward to your advice.

>What kind of testing framework would you prefer? This is the first time I have been asked for unit testing on React. I have read Jest is a common framework for unit testing on React.

Then Jest is fine.

**Comment by yizucodes** [comment]
Hi @flyingant 

Thank you MaYi for your advice. Will try to show off to the best of my abilities :-)

Cheers,
Yi

**Comment by yizucodes** [comment]
Hi @flyingant,

Can I use available libraries like react-table to build the functionalities of the table in the test?
https://github.com/tannerlinsley/react-table

Thank you for your time.

**Comment by flyingant** [comment]
@yizu100 Of course but I hope you could implement it with the native react component.

**Comment by yizucodes** [comment]
Hi @flyingant,

Hope you are well and healthy! I wanted to follow-up with you on the status of this frontend test, I would like your feedback on what I have done so far in terms of implementing the table natively and styling using SASS. 

Thank you for your guidance and I enjoyed using SASS for styling because it's a structured an easier way to write a styling sheet compared to writing pure CSS. Please let me know if you require a pull-request or clone the repo to run locally. Added documentation to the README.md for your reference. 

Thank you for your time.

Best,
Yi

**Comment by flyingant** [comment]
Feel free to send a PR(pull request).

**Comment by yizucodes** [comment]
Hi @flyingant,

Hope you had a great Easter weekend! Wanted to update you that I was able to successfully render the State or District or Township component based on what the user selects in the dropdown filter. 

Looking forward to your feedback. 

Best,
Yi
