### ISSUE TITLE
Need some clarifications on UI design

### ISSUE THREAD

**Issue by woodpig07** [Wiredcraft/test-frontend#4]
1. In the mock picture, the right icons of each cell under `Region` column are a bit confusing:
   I assume for the collapsed row the right icon should be `+` sign, for expanded row, the right icon should be `-` sign.
   Also on each `District` level, if it has township, the right label text should be `<num> Township`, am I right?
2. For the Filter and search box on the top, what is the Filter dropdown list?
   I'm assuming these filter list are to represent all three Region level `State`, `District`, `Township`, right?
3. Since there are no separate asset files for icons, can I just crop these icon directly from the mock picture? The image quality would be low, I want to make sure that's acceptable.

Thank you.

**Comment by wwayne** [comment]
@woodpig07 
1. You are totally correct.
2. Bingo, we're just playing guessing game with our candidates, just joke. Yes, the options only contain this three levels, actually the default option should be `State`. Then if you select the filter to `District`, the list will show District list, and each District can be expanded to show its Townships. If you select `Township`, just show the township list, nothing need to be shown in the expansion.
3. Sure, actually you can put any icon or logo there, empty is also acceptable.

Feel free to ask us if you have any question : )

**Comment by woodpig07** [comment]
I see.
And what about the `Search` function? I'm guessing it's only search keywords in the `Region` fields?

**Comment by wwayne** [comment]
@woodpig07 
It depends on the filter. For example, if you select `District` option in the filter, the search would only aim for District name

**Comment by woodpig07** [comment]
Hi there,
I was able to finish the most of UI and functionality, and I just put up the page [here](http://woodpig07.github.io/frontend-test/build/index.html), so maybe when you get a chance could you take a look at that to see if my understanding about these UI functions are correct.

I'll continue working on documentation and unit test.
Btw, what is `TBA for front-end requirements`?

**Comment by fraserxu** [comment]
@woodpig07 Sorry, TBA means "to be added", I just removed it.

**Comment by wwayne** [comment]
@woodpig07 good job, but I found two things need to conform with you:
1. If I open a `State` and open a `District` under it, then close this `State`, the `Townships` of the State are still in expansion, I think they should be closed too, did you do this intendedly?
   ![2016-01-16 08 45 49](https://cloud.githubusercontent.com/assets/5305874/12369208/cdde217e-bc2e-11e5-8d73-c2c5cd0c79bd.png)
2. In the search part, you do search by clicking the button after typing something in the input, but we prefer showing the result with typing. You could do some delay like waiting 1.5s to do search after user stop typing.

**Comment by woodpig07** [comment]
@wwayne 
1. yes in my previous design, the expand/collapse status of a `State` does not change the expand/collapse status of its child `District`. But what you said make sense, I just changed that behaviour.
2. Just added the function as well.

**Comment by makara** [comment]
Could you send us a PR?

**Comment by woodpig07** [comment]
PR sent.

Also for the test part, I have to admit that I never wrote test for reactjs project before until this time.
It took me some effort to get the Jest setup right, and I only get time to write a few test cases.
If you want to more test coverage, please let me know.

**Comment by makara** [comment]
Thanks. We'll get back to you very soon. Closing.
