### ISSUE TITLE
Considering icons

### ISSUE THREAD

**Issue by ArtemisSaber** [Wiredcraft/test-frontend#55]
Can I use third-party icon packs like font-awesome for icons?
Does those icons have actual functionality or just decorations
![image](https://user-images.githubusercontent.com/20559407/154801998-d1cd2b9c-069e-4b12-a691-503857cf77df.png)

**Comment by flyingant** [comment]
Feel free to try anything you like. :)

**Comment by ArtemisSaber** [comment]
> Feel free to try anything you like. :)

So does those icons have actual functionality like clickable or something? or they are just for decoration use
